<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Decatron.Desktop.Sdk\Decatron.Desktop.Sdk.csproj" />
    <ProjectReference Include="..\Decatron.Desktop.Core\Decatron.Desktop.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
</Project>
